---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mf-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mf-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mf-app
    spec:
      containers:
        - name: mf-app
          image: samadhangapat/mf_app:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SECOND_MICROSERVICE_URL
              value: http://mf-second-app:8082/api/susers
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/mfdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root 
            - name: SPRING_DATASOURCE_PASSWORD
              value: root

      restartPolicy: Always

...