---
- name: windows ping
  hosts: windows
  gather_facts: no
  vars:
    workdir: D:\work\kubernetes_practice\power_tiller_app
  tasks:
    - name: Ensure minikube is running
      win_shell: minikube status 
      register: minikube_status
    
    - name: start minikube
      win_shell: minikube start --driver=virtualbox --no-vtx-check
      when: minikube_status.rc !=0

    - name: deploy application
      win_shell: kubectl apply -f {{ workdir }}/Deployment.yml 
    
    - name: create service 
      include_tasks: Service.yml

    - name: start minikube service 
      win_shell: minikube service my-app
...
