---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inquiry-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inquiry-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: inquiry-app
    spec:
      containers:
        - name: inquiry-app
          image: samadhangapat/inquiryms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SECOND_MICROSERVICE_URL
              value: http://productdetails-app:8082/api/susers
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/mfdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root 
            - name: SPRING_DATASOURCE_PASSWORD
              value: root

      restartPolicy: Always

...