---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inquiry-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inquiry-app

  template:
    metadata:
      labels:
        app: inquiry-app
      annotations:
        date: Date
    spec:
      containers:
        - name: inquiry-app
          image: samadhangapat/inquiryms:latest
          ports:
            - containerPort: 8081
          imagePullPolicy: Always
          env:
            - name: SECOND_MICROSERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: SECOND_MICROSERVICE_URL
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: SPRING_DATASOURCE_PASSWORD
          

      restartPolicy: Always

...